# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  clean: true
  persistCredentials: true
  displayName: 'check out branch'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'github-user-options.json'
  name: GitHubUserOptions
  displayName: 'retrieve GitHub user options'

- task: oneLuckiDevJson2Variable@1
  inputs:
    jsonFile: '$(GitHubUserOptions.secureFilePath)'
    shouldPrefixVariables: false
  displayName: 'parse GitHub user options'

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    git config --global user.email '$(gitUserEmail)'
    git config --global user.name '$(gitUserName)'
    npm version patch -m 'Bump version to %s [skip ci]'
  displayName: 'npm bump version'

- script: |
    npm run build
  displayName: 'npm build'

- script: |
    git push origin HEAD:master
  displayName: 'push bumped version to origin repo'

- task: oneLuckiDevJson2Variable@1
  inputs:
    jsonFile: '$(System.DefaultWorkingDirectory)/package.json'
    shouldPrefixVariables: true
    variablePrefix: 'packageJson'
  displayName: 'read information from package.json'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      package.json
      **.md
    TargetFolder: '$(System.DefaultWorkingDirectory)/dist'
    OverWrite: true
  displayName: 'copy static files to output directory'



- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/dist'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    OverWrite: true
  displayName: 'deploy output directory contents to artifact stage'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'typedoc-plugin-devops-sourcefile'
    publishLocation: 'Container'
  displayName: 'publish to Azure Pipelines'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'DAVISOL-GmbH Full Access'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(packageJson.version)'
    releaseNotesSource: 'inline'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
  displayName: 'create release at GitHub'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(Build.ArtifactStagingDirectory)'
    customCommand: 'publish --access public'